[package]
name = "fluid-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
env_logger = "0.11.5"
glam = { version = "0.29.2", features = ["bytemuck"] }
log = "0.4.22"
pollster = "0.4.0"
wgpu = "23.0.1"
winit = "0.30.5"
